open module com.mastfrog.giulius.settings.etcd {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.settings.etcd;

    // derived from com.google.inject/guice-5.1.0 in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires transitive com.google.inject.guice;

    // derived from com.ibm.etcd/etcd-java-0.0.18 in com/ibm/etcd/etcd-java/0.0.16/etcd-java-0.0.16.pom
    requires transitive com.ibm.etcd.etcd.java;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.settings;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.giulius.threadpool;
    requires transitive com.mastfrog.util.net;

    // derived from io.netty/netty-buffer-4.1.76.Final in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires transitive io.netty.netty.buffer;

    // derived from io.netty/netty-codec-4.1.76.Final in io/netty/netty-codec/4.1.76.Final/netty-codec-4.1.76.Final.pom
    requires transitive io.netty.netty.codec;

    // derived from io.netty/netty-codec-http2-4.1.76.Final in io/netty/netty-codec-http2/4.1.76.Final/netty-codec-http2-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http2;

    // derived from io.netty/netty-codec-socks-4.1.76.Final in io/netty/netty-codec-socks/4.1.76.Final/netty-codec-socks-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.socks;

    // derived from io.netty/netty-common-4.1.76.Final in io/netty/netty-common/4.1.76.Final/netty-common-4.1.76.Final.pom
    requires transitive io.netty.netty.common;

    // derived from io.netty/netty-handler-proxy-4.1.76.Final in io/netty/netty-handler-proxy/4.1.76.Final/netty-handler-proxy-4.1.76.Final.pom
    requires transitive io.netty.netty.handler.proxy;

    // derived from io.netty/netty-transport-4.1.76.Final in io/netty/netty-transport/4.1.76.Final/netty-transport-4.1.76.Final.pom
    requires transitive io.netty.netty.transport;

    // derived from io.netty/netty-transport-native-unix-common-4.1.76.Final in io/netty/netty-transport-native-unix-common/4.1.76.Final/netty-transport-native-unix-common-4.1.76.Final.pom
    requires transitive io.netty.netty.transport.native.unix.common;

    // derived from joda-time/joda-time-2.10.14 in joda-time/joda-time/2.10.14/joda-time-2.10.14.pom
    requires transitive joda.time.joda.time;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
