// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.settings.etcd {
    exports com.mastfrog.giulius.settings.etcd;

    // derived from com.google.inject/guice-0.0.0-? in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires com.google.guice;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius;
    requires com.mastfrog.giulius.tests;
    requires javax.inject;

    // Sibling com.mastfrog/giulius-settings-3.0.0-dev
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/giulius-threadpool-3.0.0-dev
    requires com.mastfrog.giulius.threadpool;

    // Inferred from source scan
    requires com.mastfrog.net;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Transitive detected by source scan
    requires com.mastfrog.strings;

    // derived from com.ibm.etcd/etcd-java-0.0.18 in com/ibm/etcd/etcd-java/0.0.16/etcd-java-0.0.16.pom
    requires etcd.java;

    // derived from io.netty/netty-buffer-0.0.0-? in io/netty/netty-buffer/4.1.76.Final/netty-buffer-4.1.76.Final.pom
    requires io.netty.buffer;

    // derived from io.netty/netty-codec-4.1.76.Final in io/netty/netty-codec/4.1.76.Final/netty-codec-4.1.76.Final.pom
    requires io.netty.codec;

    // derived from io.netty/netty-codec-http2-4.1.76.Final in io/netty/netty-codec-http2/4.1.76.Final/netty-codec-http2-4.1.76.Final.pom
    requires io.netty.codec.http2;

    // derived from io.netty/netty-codec-socks-4.1.76.Final in io/netty/netty-codec-socks/4.1.76.Final/netty-codec-socks-4.1.76.Final.pom
    requires io.netty.codec.socks;

    // derived from io.netty/netty-common-4.1.76.Final in io/netty/netty-common/4.1.76.Final/netty-common-4.1.76.Final.pom
    requires io.netty.common;

    // derived from io.netty/netty-handler-proxy-4.1.76.Final in io/netty/netty-handler-proxy/4.1.76.Final/netty-handler-proxy-4.1.76.Final.pom
    requires io.netty.handler.proxy;

    // derived from io.netty/netty-transport-0.0.0-? in io/netty/netty-transport/4.1.76.Final/netty-transport-4.1.76.Final.pom
    requires io.netty.transport;

    // derived from io.netty/netty-transport-native-unix-common-4.1.76.Final in io/netty/netty-transport-native-unix-common/4.1.76.Final/netty-transport-native-unix-common-4.1.76.Final.pom
    requires io.netty.transport.unix.common;

    // Inferred from test-source-scan
    requires junit;

    // derived from joda-time/joda-time-2.10.14 in joda-time/joda-time/2.10.14/joda-time-2.10.14.pom
    requires org.joda.time;

}
